In [ ]:
# 1. Assign your Name to variable name and Age to variable age. Make a Python program that
#prints your name and age.

In [1]:
name="Riddhika"
age = 21
print(name)
print(age)

Riddhika
21


In [ ]:
#2.X="Datascience is used to extract meaningful insights."Split the string

In [2]:
X="Datascience is used to extract meaningful insights."
print(X.split())

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [ ]:
#3.Make a function that gives multiplication of two numbers

In [3]:
def multiplication(a,b):
    return a*b
print(multiplication(23,5))

115


In [ ]:
#4.Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [6]:
states = {'TamilNadu':'Chennai','Kerala':'Thiruvananthapuram','Karnataka':'Banglore','Maharashtra':'Mumbai','Bihar':'Patna'}
for key,value in states.items():
    print("Key : ",key,",value : ",value)


Key :  TamilNadu ,value :  Chennai
Key :  Kerala ,value :  Thiruvananthapuram
Key :  Karnataka ,value :  Banglore
Key :  Maharashtra ,value :  Mumbai
Key :  Bihar ,value :  Patna


In [ ]:
#5.Create a list of 1000 numbers using range function

In [7]:
numbers = []
for i in range(1000):
    numbers.append(i)
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
#6.Create an identity matrix of dimension 4 by 4

In [8]:
import numpy as np

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#7.Create a 3x3 matrix with values ranging from 1 to 9

In [12]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#8.Create 2 similar dimensional array and perform sum on them.

In [17]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [16]:
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [ ]:
#9.Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [21]:
from datetime import datetime, timedelta

start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)

# Iterate through the dates
current_date = start_date
while current_date <= end_date:
    print(current_date.strftime("%Y-%m-%d"))
    current_date += timedelta(days=1)

2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


In [ ]:
#10.Given a dictionary, convert it into corresponding dataframe and display it
#dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [18]:
import pandas as pd

In [19]:
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [20]:
data = pd.DataFrame(dictionary)
data

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240